"""add role to users table

Revision ID: 04414ea38cdd
Revises: 8f55c6c82916
Create Date: 2025-08-22 17:27:38.434600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04414ea38cdd'
down_revision: Union[str, Sequence[str], None] = '8f55c6c82916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_column('user_accounts', 'role')
    # ### end Alembic commands ###
